classes:
- linux.system.repo.mcp.apt_mirantis.docker_legacy
- linux.system.repo.mcp.extra
- linux.system.repo.mcp.apt_mirantis.ubuntu
- linux.system.repo.mcp.apt_mirantis.saltstack
- kubernetes.pool.cluster
- salt.minion.cert.k8s_client
- salt.minion.cert.etcd_client

parameters:
  kubernetes:
    pool:
      network:
        calico:
          no_default_pools: false
          etcd:
            ssl:
              enabled: True
          policy:
            enabled: False
          prometheus:
            enabled: true
  linux:
    system:
      kernel:
        sysctl:
          # The default operating system limits on mmap counts is likely to be too low, which may result in out of memory exceptions.
          vm.max_map_count: 262144
